[
   without-arg --  _1,
   with-arg -- H[_1 _2],
   label-def -- Hhs=0[_1 ":"],
   instruction -- R["" Hhs=0[_1 ";"]],
   number -- H[_1],
   code -- H[_1],
   aterm -- H[_1],
   label -- H[_1],
   program -- V [Vis=2["{"_1 ] "}"],
   program.1:iter-star -- A(r,l)hs=1[_1],
   ATerms -- Hhs=0["[" _1 "]"],
   IntCon -- H[_1],
   Literal -- H[_1],
   ACon-Ann -- Hhs=0[_1 _2],
   ACon-No-Ann -- H[_1],
   ATermList-Ann -- Hhs=0[_1 _2],
   ATermList-No-Ann -- H[_1],
   AFun-Ann -- Hhs=0[_1 _2],
   AFun-No-Ann -- H[_1],
   Appl-Ann -- Hhs=0[_1 "(" _2 ")" _3],
   Appl-No-Ann -- Hhs=0[_1 "(" _2 ")"],
   Placeholder-No-Ann -- Hhs=0["<" _1 ">"],
   Placeholder-Ann -- Hhs=0["<" _1 ">" _2]
]
