Int Interface Reference
Public Methods
long intValue ()
Int plus (Int n)
Int minus (Int n)
Int monus (Int n)
Int times (Int n)
Empty greater (Int n) throws Exceptional
Empty greaterOrEq (Int n) throws Exceptional
Empty less (Int n) throws Exceptional
Empty lessOrEq (Int n) throws Exceptional
Member Function Documentation
Empty Int::greater (Int n)
Reimplemented in IntImpl.
Empty Int::greaterOrEq (Int n)
Reimplemented in IntImpl.
long Int::intValue ()
Reimplemented in IntImpl.
Referenced by IntImpl::greater(), IntImpl::greaterOrEq(), IntImpl::less(), IntImpl::lessOrEq(), IntImpl::minus(), IntImpl::monus(), IntImpl::plus(), and IntImpl::times().
Empty Int::less (Int n)
Reimplemented in IntImpl.
Empty Int::lessOrEq (Int n)
Reimplemented in IntImpl.
Int Int::minus (Int n)
Reimplemented in IntImpl.
Int Int::monus (Int n)
Reimplemented in IntImpl.
Int Int::plus (Int n)
Reimplemented in IntImpl.
Int Int::times (Int n)
Reimplemented in IntImpl.
The documentation for this interface was generated from the following file:
Int.java