DataFactory Interface Reference
Public Methods
Empty makeEmpty ()
Data makeTuple (DataValue dataValue, Data data)
Int makeInt (long n)
Token makeToken (String s)
Bool makeBool (boolean b)
MessageTag makeMessageTag (String s)
List makeList1 (DataValue dataValue)
List makeList0 ()
Action makeAction (Enactable enactable)
Bindings makeNoBindings ()
Bindings makeBindings (Token token, Bindable bindable)
Agent makeAgent ()
Cell makeCell ()
Member Function Documentation
Action DataFactory::makeAction (Enactable enactable)
Reimplemented in PureFactory.
Agent DataFactory::makeAgent ()
Reimplemented in PureFactory.
Referenced by Schedule::activate().
Bindings DataFactory::makeBindings (Token token, Bindable bindable)
Reimplemented in PureFactory.
Bool DataFactory::makeBool (boolean b)
Reimplemented in PureFactory.
Cell DataFactory::makeCell ()
Reimplemented in PureFactory.
Referenced by Store::create().
Empty DataFactory::makeEmpty ()
Reimplemented in PureFactory.
Referenced by Schedule::deactivate(), TaggedBuffers::dequeue(), Store::destroy(), Store::inspect(), Schedule::receive(), Schedule::send(), and Store::update().
Int DataFactory::makeInt (long n)
Reimplemented in PureFactory.
Referenced by Schedule::chooseNatural(), and Schedule::currentTime().
List DataFactory::makeList0 ()
Reimplemented in PureFactory.
List DataFactory::makeList1 (DataValue dataValue)
Reimplemented in PureFactory.
MessageTag DataFactory::makeMessageTag (String s)
Reimplemented in PureFactory.
Bindings DataFactory::makeNoBindings ()
Reimplemented in PureFactory.
Token DataFactory::makeToken (String s)
Reimplemented in PureFactory.
Data DataFactory::makeTuple (DataValue dataValue, Data data)
Reimplemented in PureFactory.
The documentation for this interface was generated from the following file:
DataFactory.java