List Interface Reference
Public Methods
DataValue head () throws Exceptional
List tail ()
List insert (DataValue dataValue)
List append (DataValue dataValue)
List concat (List list)
Member Function Documentation
List List::append (DataValue dataValue)
Reimplemented in ListImpl.
Referenced by ListImpl::append().
List List::concat (List list)
Reimplemented in ListImpl.
Referenced by ListImpl::concat().
DataValue List::head ()
Reimplemented in ListImpl.
List List::insert (DataValue dataValue)
Reimplemented in ListImpl.
Referenced by DataImpl::tupleToList().
List List::tail ()
Reimplemented in ListImpl.
The documentation for this interface was generated from the following file:
List.java