PureFactory Class Reference
Public Methods
PureFactory ()
Int makeInt (long n)
Token makeToken (String s)
Bool makeBool (boolean b)
MessageTag makeMessageTag (String s)
List makeList0 ()
List makeList1 (DataValue dataValue)
Bindings makeNoBindings ()
Agent makeAgent ()
Cell makeCell ()
Empty makeEmpty ()
Data makeTuple (DataValue dataValue, Data data)
Action makeAction (Enactable enactable)
Constructor & Destructor Documentation
PureFactory::PureFactory () [inline]
Definition at line 9 of file PureFactory.java.
00009                          {
00010         EmptyImpl.init(this);
00011         ListImpl.init(this);
00012     }
Member Function Documentation
Action PureFactory::makeAction (Enactable enactable) [inline]
Reimplemented from DataFactory.
Definition at line 51 of file PureFactory.java.
00051                                                   {
00052         return new ActionImpl(this, enactable);
00053     }
Agent PureFactory::makeAgent () [inline]
Reimplemented from DataFactory.
Definition at line 37 of file PureFactory.java.
00037                              {
00038         return new AgentImpl(this);
00039     }
Bool PureFactory::makeBool (boolean b) [inline]
Reimplemented from DataFactory.
Definition at line 20 of file PureFactory.java.
Referenced by BoolImpl::not().
00020                                     {
00021         return new BoolImpl(this, b);
00022     }
Cell PureFactory::makeCell () [inline]
Reimplemented from DataFactory.
Definition at line 40 of file PureFactory.java.
00040                            {
00041         return new CellImpl(this);
00042     }
Empty PureFactory::makeEmpty () [inline]
Reimplemented from DataFactory.
Definition at line 43 of file PureFactory.java.
Referenced by BindingsImpl::bound(), DataValueImpl::component(), ActionImpl::enact(), TextImpl::equals(), ListImpl::equals(), IntImpl::equals(), DataValueImpl::equals(), BoolImpl::equals(), ActionImpl::equals(), EmptyImpl::first(), IntImpl::greater(), IntImpl::greaterOrEq(), ListImpl::head(), IntImpl::less(), IntImpl::lessOrEq(), and DataValueImpl::rest().
00043                              {
00044         return EmptyImpl.empty();
00045     }
Int PureFactory::makeInt (long n) [inline]
Reimplemented from DataFactory.
Definition at line 14 of file PureFactory.java.
00014                                {
00015         return new IntImpl(this, n);
00016     }
List PureFactory::makeList0 () [inline]
Reimplemented from DataFactory.
Definition at line 26 of file PureFactory.java.
Referenced by EmptyImpl::tupleToList().
00026                             {
00027         return ListImpl.empty();
00028     }
List PureFactory::makeList1 (DataValue dataValue) [inline]
Reimplemented from DataFactory.
Definition at line 30 of file PureFactory.java.
Referenced by DataValueImpl::tupleToList().
00030                                                {
00031         return new ListImpl(this,dataValue);
00032     }
MessageTag PureFactory::makeMessageTag (String s) [inline]
Reimplemented from DataFactory.
Definition at line 23 of file PureFactory.java.
00023                                                {
00024         return new MessageTagImpl(this,s);
00025     }
Bindings PureFactory::makeNoBindings () [inline]
Reimplemented from DataFactory.
Definition at line 34 of file PureFactory.java.
Referenced by ActionImpl::enact().
00034                                      {
00035         return new BindingsImpl(this);
00036     }
Token PureFactory::makeToken (String s) [inline]
Reimplemented from DataFactory.
Definition at line 17 of file PureFactory.java.
00017                                      {
00018         return new TokenImpl(this, s);
00019     }
Data PureFactory::makeTuple (DataValue dataValue, Data data) [inline]
Reimplemented from DataFactory.
Definition at line 47 of file PureFactory.java.
Referenced by DataValueImpl::concat().
00047                                                           {
00048         return new DataImpl(this, dataValue, data);
00049     }
The documentation for this class was generated from the following file:
PureFactory.java