Data Interface Reference
Public Methods
Data concat (Data data)
List tupleToList ()
DataValue first () throws Exceptional
Data rest ()
DataValue component (int n) throws Exceptional
Action provide ()
Member Function Documentation
DataValue Data::component (int n)
Reimplemented in DataImpl, and DataValueImpl.
Referenced by DataImpl::component().
Data Data::concat (Data data)
Reimplemented in DataImpl, and DataValueImpl.
Referenced by DataImpl::concat(), AndExceptionally::_AndExceptionally::enact(), And::_And::enact(), and AndThen::_AndThen::enact().
DataValue Data::first ()
Reimplemented in DataImpl, DataValueImpl, and EmptyImpl.
Action Data::provide ()
Reimplemented in DataImpl.
Data Data::rest ()
Reimplemented in DataImpl, and DataValueImpl.
List Data::tupleToList ()
Reimplemented in DataImpl, DataValueImpl, and EmptyImpl.
Referenced by DataImpl::tupleToList().
The documentation for this interface was generated from the following file:
Data.java