Enactable Interface Reference
Public Methods
Data enact (Data data, Bindings bindings) throws Exceptional, Failed
Member Function Documentation
Data Enactable::enact (Data data, Bindings bindings)
Reimplemented in Then::_Then, AndThen::_AndThen, And::_And, Exceptionally::_Exceptionally, AndExceptionally::_AndExceptionally, Otherwise::_Otherwise, Hence::_Hence, Indivisibly::_Indivisibly, and Provide::_Provide.
Referenced by Indivisibly::enact(), Hence::enact(), Otherwise::enact(), AndExceptionally::enact(), Exceptionally::enact(), And::enact(), AndThen::enact(), Then::enact(), and ActionImpl::enact().
The documentation for this interface was generated from the following file:
Enactable.java