Action Interface Reference
Public Methods
Enactable enactableValue ()
Data enact () throws Exceptional, Failed
Action then (Action action)
Action andThen (Action action)
Action and (Action action)
Action exceptionally (Action action)
Action andExceptionally (Action action)
Action otherwise (Action action)
Action hence (Action action)
Action indivisibly ()
Member Function Documentation
Action Action::and (Action action)
Reimplemented in ActionImpl.
Action Action::andExceptionally (Action action)
Reimplemented in ActionImpl.
Action Action::andThen (Action action)
Reimplemented in ActionImpl.
Data Action::enact ()
Reimplemented in ActionImpl, and ActionImpl.
Referenced by ActionImpl::run().
Enactable Action::enactableValue ()
Reimplemented in ActionImpl.
Referenced by ActionImpl::and(), ActionImpl::andExceptionally(), ActionImpl::andThen(), ActionImpl::exceptionally(), ActionImpl::hence(), ActionImpl::otherwise(), and ActionImpl::then().
Action Action::exceptionally (Action action)
Reimplemented in ActionImpl.
Action Action::hence (Action action)
Reimplemented in ActionImpl.
Action Action::indivisibly ()
Reimplemented in ActionImpl.
Action Action::otherwise (Action action)
Reimplemented in ActionImpl.
Action Action::then (Action action)
Reimplemented in ActionImpl.
The documentation for this interface was generated from the following file:
Action.java