/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (ailc-opt.c)
 *  
 *  It has been AutoGen-ed  Wednesday July 10, 2002 at 06:55:42 PM CEST
 *  From the definitions    ailc-opt.def
 *  and the template file   options
 */
#include "ailc-opt.h"

tSCC zCopyright[] =
       "ailc copyright (c)  Tijs van der Storm, all rights reserved";
tSCC zCopyrightNotice[] =
       "ailc is free software.\n\n\
You may redistribute it and/or modify it under the terms of the\n\
GNU General Public License, as published by the Free Software\n\
Foundation; either version 2, or (at your option) any later version.\n\n\
ailc is distributed in the hope that it will be useful,\n\
but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\
See the GNU General Public License for more details.\n\n\
You should have received a copy of the GNU General Public License\n\
along with ailc.  See the file \"COPYING\".  If not,\n\
write to:  The Free Software Foundation, Inc.,\n\
           59 Temple Place - Suite 330,\n\
           Boston,  MA  02111-1307, USA.";

extern tUsageProc optionUsage;


#ifndef NULL
#  define NULL 0x0
#endif
#ifndef EXIT_SUCCESS
#  define  EXIT_SUCCESS 0
#endif
#ifndef EXIT_FAILURE
#  define  EXIT_FAILURE 1
#endif
/*
 *  Input option description:
 */
tSCC    zInputText[] =
        "input parsed AIL from file";
tSCC    zInput_NAME[]              = "INPUT";
#define zNotInput_Pfx                NULL
#define zNotInput_Name               NULL
tSCC    zInput_Name[]              = "input";
#define INPUT_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Output option description:
 */
tSCC    zOutputText[] =
        "output ABF to file";
tSCC    zOutput_NAME[]             = "OUTPUT";
#define zNotOutput_Pfx               NULL
#define zNotOutput_Name              NULL
tSCC    zOutput_Name[]             = "output";
#define OUTPUT_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Verbose option description:
 */
tSCC    zVerboseText[] =
        "";
tSCC    zVerbose_NAME[]            = "VERBOSE";
#define zNotVerbose_Pfx              NULL
#define zNotVerbose_Name             NULL
tSCC    zVerbose_Name[]            = "verbose";
#define VERBOSE_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Generate_Api option description with
 *  "Must also have options" and "Incompatible options":
 */
tSCC    zGenerate_ApiText[] =
        "generate AIL c-api";
tSCC    zGenerate_Api_NAME[]       = "GENERATE_API";
#define zNotGenerate_Api_Pfx         NULL
#define zNotGenerate_Api_Name        NULL
tSCC    zGenerate_Api_Name[]       = "generate-api";
static const int
    aGenerate_ApiMustList[] = {
    INDEX_OPT_NAME, NO_EQUIVALENT };
#define GENERATE_API_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Name option description:
 */
tSCC    zNameText[] =
        "stem for generated c-api";
tSCC    zName_NAME[]               = "NAME";
#define zNotName_Pfx                 NULL
#define zNotName_Name                NULL
tSCC    zName_Name[]               = "name";
#define NAME_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Prefix option description:
 */
tSCC    zPrefixText[] =
        "prefix string for generated c-api";
tSCC    zPrefix_NAME[]             = "PREFIX";
#define zNotPrefix_Pfx               NULL
#define zNotPrefix_Name              NULL
tSCC    zPrefix_Name[]             = "prefix";
tSCC    zPrefixDefaultArg[]          = "AIL";
#define PREFIX_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Ail_List option description:
 */
tSCC    zAil_ListText[] =
        "override default AIL instruction list";
tSCC    zAil_List_NAME[]           = "AIL_LIST";
#define zNotAil_List_Pfx             NULL
#define zNotAil_List_Name            NULL
tSCC    zAil_List_Name[]           = "ail-list";
tSCC    zAil_ListDefaultArg[]        = "./ail-ins.baf";
#define AIL_LIST_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Help option description:
 */
tSCC zHelpText[]  = "Display usage information and exit";
tSCC zHelp_Name[] = "help";

/*
 *  More_Help option description:
 */
tSCC zMore_HelpText[]  = "Extended usage information passed thru pager";
tSCC zMore_Help_Name[] = "more-help";

/*
 *  Version option description:
 */
tSCC zVersionText[]    = "Output version information and exit";
tSCC zVersion_Name[]   = "version";
/*
 *  These are always callable, whether
 *  TEST_AILC_OPTS is defined or not
 */
static tOptProc doUsageOpt;
extern tOptProc doVersion;
extern tOptProc doPagedUsage;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Ailc Option Descriptions.
 */
static tOptDesc optDesc[ OPTION_CT ] = {
  {  /* entry idx, value */ 0, VALUE_OPT_INPUT,
     /* equiv idx, value */ 0, VALUE_OPT_INPUT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INPUT_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zInputText,  zInput_NAME,
                            zInput_Name,
     /* disablement strs */ zNotInput_Name, zNotInput_Pfx },

  {  /* entry idx, value */ 1, VALUE_OPT_OUTPUT,
     /* equiv idx, value */ 1, VALUE_OPT_OUTPUT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OUTPUT_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zOutputText,  zOutput_NAME,
                            zOutput_Name,
     /* disablement strs */ zNotOutput_Name, zNotOutput_Pfx },

  {  /* entry idx, value */ 2, VALUE_OPT_VERBOSE,
     /* equiv idx, value */ 2, VALUE_OPT_VERBOSE,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VERBOSE_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zVerboseText,  zVerbose_NAME,
                            zVerbose_Name,
     /* disablement strs */ zNotVerbose_Name, zNotVerbose_Pfx },

  {  /* entry idx, value */ 3, VALUE_OPT_GENERATE_API,
     /* equiv idx, value */ 3, VALUE_OPT_GENERATE_API,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ GENERATE_API_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aGenerate_ApiMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zGenerate_ApiText,  zGenerate_Api_NAME,
                            zGenerate_Api_Name,
     /* disablement strs */ zNotGenerate_Api_Name, zNotGenerate_Api_Pfx },

  {  /* entry idx, value */ 4, VALUE_OPT_NAME,
     /* equiv idx, value */ 4, VALUE_OPT_NAME,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NAME_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zNameText,  zName_NAME,
                            zName_Name,
     /* disablement strs */ zNotName_Name, zNotName_Pfx },

  {  /* entry idx, value */ 5, VALUE_OPT_PREFIX,
     /* equiv idx, value */ 5, VALUE_OPT_PREFIX,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PREFIX_FLAGS,
     /* last opt argumnt */ (char*)zPrefixDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zPrefixText,  zPrefix_NAME,
                            zPrefix_Name,
     /* disablement strs */ zNotPrefix_Name, zNotPrefix_Pfx },

  {  /* entry idx, value */ 6, VALUE_OPT_AIL_LIST,
     /* equiv idx, value */ 6, VALUE_OPT_AIL_LIST,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ AIL_LIST_FLAGS,
     /* last opt argumnt */ (char*)zAil_ListDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zAil_ListText,  zAil_List_NAME,
                            zAil_List_Name,
     /* disablement strs */ zNotAil_List_Name, zNotAil_List_Pfx },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_MAY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_INIT,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doVersion,
     /* desc, NAME, name */ zVersionText, NULL, zVersion_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zHelpText, NULL, zHelp_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ doPagedUsage,
     /* desc, NAME, name */ zMore_HelpText, NULL, zMore_Help_Name,
     /* disablement strs */ NULL, NULL }
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Ailc Option Environment
 */
tSCC   zPROGNAME[]   = "AILC";
tSCC   zUsageTitle[] =
"ailc - AIL to ABF compiler - Ver. 0.1\n\
USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]...\n";
#define zRcName     NULL
#define apzHomeList NULL
tSCC   zExplain[]    = "\n\
E.g.: ail2baf -i action.ail --output action.abf.\n";

tSCC    zDetail[]     = "\n\
Convert parsed Abstract Intermediate Language to bytecode.\n\
The input file must be a valid AsfixME parse-tree representing\n\
A program in AIL language. Output is a binary representation of\n\
the program to be processed by an AIL machine.\n";

extern  tUsageProc optionUsage;
tSCC    zFullVersion[] = AILC_FULL_VERSION;

tOptions ailcOptions = {
    OPTIONS_STRUCT_VERSION,
    NULL,         NULL,        zPROGNAME,
    zRcName,      zCopyright,  zCopyrightNotice,
    zFullVersion, apzHomeList, zUsageTitle,
    zExplain,     zDetail,     NULL,
    optionUsage,
    ( OPTPROC_NONE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NO_ARGS ),
    0, NULL,
    { INDEX_OPT_MORE_HELP,
       0 /* no option state saving */,
      NO_EQUIVALENT /* no '-#' option */,
      NO_EQUIVALENT /* no default option */ },
    OPTION_CT, 7 /* user option count */,
    optDesc
};

/*
 *  Create the static procedure(s) declared above.
 */
static void
#ifdef __cplusplus
doUsageOpt(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
#else
doUsageOpt( pOpts, pOD )
    tOptions*  pOpts;
    tOptDesc*  pOD;
#endif
{
    USAGE( EXIT_SUCCESS );
}
#if defined( TEST_AILC_OPTS )

    int
main( int argc, char** argv )
{
    (void)optionProcess( &ailcOptions, argc, argv );
    putBourneShell( &ailcOptions );
    return EXIT_SUCCESS;
}
#endif  /* defined TEST_AILC_OPTS */
