/* This C code is generated by the asf compiler version 2.5 */

#include  "asc-support-me.h"
static Symbol lf_1sym ;
static ATerm lf_1 ( ATerm arg1 ) ;
static Symbol lf_2sym ;
static ATerm lf_2 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_list_3sym ;
static ATerm lf_list_3 ( ATerm arg1 ) ;
static Symbol lf_4sym ;
static ATerm lf_4 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_5sym ;
static ATerm lf_5 ( ATerm arg1 ) ;
static Symbol lf_6sym ;
static ATerm lf_6 ( ) ;
void register_obs_data___AN_K_Data_Contract ( ) {
lf_1sym = ATmakeSymbol ( "prod([cf(sort(\"Datum\"))],cf(sort(\"Data\")),attrs([term(cons(\"datum\"))]))"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_1sym ) ;
lf_2sym = ATmakeSymbol ( "prod([cf(sort(\"Data\")),cf(opt(layout)),lit(\"++\"),cf(opt(layout)),cf(sort(\"Data\"))],cf(sort(\"Data\")),attrs([prefer,assoc(left)]))" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_2sym ) ;
lf_list_3sym = ATmakeSymbol ( "list(cf(iter-sep(sort(\"Data\"),lit(\",\"))))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_list_3sym ) ;
lf_4sym = ATmakeSymbol ( "prod([cf(sort(\"Data\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(iter-sep(sort(\"Data\"),lit(\",\")))],cf(iter-sep-n(sort(\"Data\"),lit(\",\"),2)),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_4sym ) ;
lf_5sym = ATmakeSymbol ( "prod([lit(\"(\"),cf(opt(layout)),cf(iter-sep-n(sort(\"Data\"),lit(\",\"),2)),cf(opt(layout)),lit(\")\")],cf(sort(\"Data\")),attrs([term(cons(\"tuple\"))]))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_5sym ) ;
lf_6sym = ATmakeSymbol ( "prod([lit(\"(\"),cf(opt(layout)),lit(\")\")],cf(sort(\"Data\")),attrs([prefer,term(cons(\"empty\"))]))" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_6sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Datum\"))],cf(sort(\"Data\")),attrs([term(cons(\"datum\"))]))" ) , lf_1 , lf_1sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Data\")),cf(opt(layout)),lit(\"++\"),cf(opt(layout)),cf(sort(\"Data\"))],cf(sort(\"Data\")),attrs([prefer,assoc(left)]))" ) , lf_2 , lf_2sym ) ;
register_prod ( ATparse ( "list(cf(iter-sep(sort(\"Data\"),lit(\",\"))))" ) , lf_list_3 , lf_list_3sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Data\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(iter-sep(sort(\"Data\"),lit(\",\")))],cf(iter-sep-n(sort(\"Data\"),lit(\",\"),2)),no-attrs)" ) , lf_4 , lf_4sym ) ;
register_prod ( ATparse ( "prod([lit(\"(\"),cf(opt(layout)),cf(iter-sep-n(sort(\"Data\"),lit(\",\"),2)),cf(opt(layout)),lit(\")\")],cf(sort(\"Data\")),attrs([term(cons(\"tuple\"))]))" ) , lf_5 , lf_5sym ) ;
register_prod ( ATparse ( "prod([lit(\"(\"),cf(opt(layout)),lit(\")\")],cf(sort(\"Data\")),attrs([prefer,term(cons(\"empty\"))]))" ) , lf_6 , lf_6sym ) ;
}
void resolve_obs_data___AN_K_Data_Contract ( ) {
}
void init_obs_data___AN_K_Data_Contract ( ) {
}
ATerm lf_2 ( ATerm arg0 , ATerm arg1 ) {
{
ATerm tmp [ 1 ] ;
FUNC_ENTRY ( lf_2sym , ATmakeAppl ( lf_2sym , arg0 , arg1 ) ) ;
if ( check_sym ( arg0 , lf_1sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( arg1 , lf_1sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
FUNC_EXIT ( make_nf1 ( lf_5sym , make_nf2 ( lf_4sym , arg0 , make_nf1 ( lf_list_3sym , make_list ( arg1 ) ) ) ) ) ;
}
}
if ( check_sym ( arg1 , lf_5sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
if ( check_sym ( atmp10 , lf_4sym ) ) {
{
ATerm atmp100 = arg_0 ( atmp10 ) ;
{
ATerm atmp101 = arg_1 ( atmp10 ) ;
if ( check_sym ( atmp101 , lf_list_3sym ) ) {
{
ATerm atmp1010 = arg_0 ( atmp101 ) ;
if ( not_empty_list ( atmp1010 ) ) {
FUNC_EXIT ( make_nf1 ( lf_5sym , make_nf2 ( lf_4sym , arg0 , make_nf1 ( lf_list_3sym , cons ( make_list ( atmp100 ) , make_list ( atmp1010 ) ) ) ) ) ) ;
}
}
}
}
}
}
}
}
}
}
if ( check_sym ( arg0 , lf_5sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp00 , lf_4sym ) ) {
{
ATerm atmp000 = arg_0 ( atmp00 ) ;
{
ATerm atmp001 = arg_1 ( atmp00 ) ;
if ( check_sym ( atmp001 , lf_list_3sym ) ) {
{
ATerm atmp0010 = arg_0 ( atmp001 ) ;
if ( check_sym ( arg1 , lf_1sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
if ( not_empty_list ( atmp0010 ) ) {
FUNC_EXIT ( make_nf1 ( lf_5sym , make_nf2 ( lf_4sym , atmp000 , make_nf1 ( lf_list_3sym , cons ( make_list ( atmp0010 ) , make_list ( arg1 ) ) ) ) ) ) ;
}
}
}
if ( check_sym ( arg1 , lf_5sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
if ( check_sym ( atmp10 , lf_4sym ) ) {
{
ATerm atmp100 = arg_0 ( atmp10 ) ;
{
ATerm atmp101 = arg_1 ( atmp10 ) ;
if ( check_sym ( atmp101 , lf_list_3sym ) ) {
{
ATerm atmp1010 = arg_0 ( atmp101 ) ;
if ( not_empty_list ( atmp0010 ) ) {
if ( not_empty_list ( atmp1010 ) ) {
FUNC_EXIT ( make_nf1 ( lf_5sym , make_nf2 ( lf_4sym , atmp000 , make_nf1 ( lf_list_3sym , cons ( make_list ( atmp0010 ) , cons ( make_list ( atmp100 ) , make_list ( atmp1010 ) ) ) ) ) ) ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
( tmp [ 0 ] = make_nf0 ( lf_6sym ) ) ;
if ( term_equal ( arg1 , tmp [ 0 ] ) ) {
FUNC_EXIT ( arg0 ) ;
}
if ( term_equal ( arg0 , tmp [ 0 ] ) ) {
FUNC_EXIT ( arg1 ) ;
}
FUNC_EXIT ( make_nf1 ( lf_5sym , make_nf2 ( lf_4sym , arg0 , make_nf1 ( lf_list_3sym , make_list ( arg1 ) ) ) ) ) ;
FUNC_EXIT ( make_nf2 ( lf_2sym , arg0 , arg1 ) ) ;
}
}
ATerm lf_6 ( ) {
CONS_ENTRY ( lf_6sym , ATmakeAppl0 ( lf_6sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_6sym ) ) ;
}
ATerm lf_5 ( ATerm arg0 ) {
CONS_ENTRY ( lf_5sym , ATmakeAppl ( lf_5sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_5sym , arg0 ) ) ;
}
ATerm lf_4 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_4sym , ATmakeAppl ( lf_4sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_4sym , arg0 , arg1 ) ) ;
}
ATerm lf_list_3 ( ATerm arg0 ) {
CONS_ENTRY ( lf_list_3sym , ATmakeAppl ( lf_list_3sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_list_3sym , arg0 ) ) ;
}
ATerm lf_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_1sym , ATmakeAppl ( lf_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_1sym , arg0 ) ) ;
}
#ifdef ASF_MAIN
int main(int argc, char *argv[])                         
{                                                        
  ATerm bottom;
  return asc_support_main(&bottom, argc, argv,           
                          register_obs_data___AN_K_Data_Contract,                   
                          resolve_obs_data___AN_K_Data_Contract,                    
                          init_obs_data___AN_K_Data_Contract
);}                                                        
#endif                                                   

