.TH "AbstractInfixCombinator" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractInfixCombinator \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBActionImpl\fP.
.PP
Inherited by \fBAnd\fP, \fBAndExceptionally\fP, \fBAndThen\fP, \fBExceptionally\fP, \fBHence\fP, \fBOtherwise\fP, and \fBThen\fP.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.