.TH "AbstractPrefixCombinator" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractPrefixCombinator \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBActionImpl\fP.
.PP
Inherited by \fBIndivisibly\fP.
.PP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEnactable\fP \fBenactable1\fP"
.br
.in -1c
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "\fBEnactable\fP AbstractPrefixCombinator::enactable1\fC [protected]\fP"
.PP
Definition at line 8 of file AbstractPrefixCombinator.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.