.TH "AbstractEnactable" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractEnactable \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBEnactable\fP.
.PP
.SS "Protected Methods"

.in +1c
.ti -1c
.RI "\fBData\fP \fBfail\fP () throws \fBFailed\fP"
.br
.ti -1c
.RI "\fBData\fP \fBraise\fP (\fBData\fP data) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBData\fP \fBcatchExceptional\fP (\fBException\fP e) throws \fBFailed\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDataFactory\fP \fBfactory\fP"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBData\fP AbstractEnactable::catchExceptional (\fBException\fP e)\fC [protected]\fP"
.PP
Definition at line 25 of file AbstractEnactable.java.
.SS "\fBData\fP AbstractEnactable::fail ()\fC [protected]\fP"
.PP
Definition at line 14 of file AbstractEnactable.java.
.SS "\fBData\fP AbstractEnactable::raise (\fBData\fP data)\fC [protected]\fP"
.PP
Definition at line 19 of file AbstractEnactable.java.
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "\fBDataFactory\fP AbstractEnactable::factory\fC [protected]\fP"
.PP
Definition at line 12 of file AbstractEnactable.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.