.TH "AndThen" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AndThen \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBAbstractInfixCombinator\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBAndThen\fP (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.br
.ti -1c
.RI "\fBData\fP \fBenact\fP (\fBData\fP data, \fBBindings\fP bindings) throws \fBExceptional\fP, \fBFailed\fP"
.br
.ti -1c
.RI "\fBAndThen\fP (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "AndThen::AndThen (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.PP
Definition at line 73 of file AbstractAction.java.
.SS "AndThen::AndThen (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.PP
Definition at line 98 of file ActionImpl.java.
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBData\fP AndThen::enact (\fBData\fP data, \fBBindings\fP bindings)"
.PP
Definition at line 76 of file AbstractAction.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.