.TH "Bindings" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bindings \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatum\fP.
.PP
Inherited by \fBBindingsImpl\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "Map \fBmapValue\fP ()"
.br
.ti -1c
.RI "\fBBindable\fP \fBbound\fP (\fBToken\fP token) throws \fBExceptional\fP"
.br
.ti -1c
.RI "Bindings \fBoverriding\fP (Bindings bindings)"
.br
.ti -1c
.RI "Bindings \fBdisjointUnion\fP (Bindings bindings)"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBBindable\fP Bindings::bound (\fBToken\fP token)"
.PP
Reimplemented in \fBBindingsImpl\fP.
.SS "Bindings Bindings::disjointUnion (Bindings bindings)"
.PP
Reimplemented in \fBBindingsImpl\fP.
.SS "Map Bindings::mapValue ()"
.PP
Reimplemented in \fBBindingsImpl\fP.
.PP
Referenced by BindingsImpl::disjointUnion(), and BindingsImpl::overriding().
.PP
.SS "Bindings Bindings::overriding (Bindings bindings)"
.PP
Reimplemented in \fBBindingsImpl\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.