.TH "BindingsImpl" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BindingsImpl \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatumImpl\fP, and \fBBindings\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "Map \fBmapValue\fP ()"
.br
.ti -1c
.RI "\fBBindable\fP \fBbound\fP (\fBToken\fP token) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBBindings\fP \fBoverriding\fP (\fBBindings\fP bindings)"
.br
.ti -1c
.RI "\fBBindings\fP \fBdisjointUnion\fP (\fBBindings\fP bindings)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBBindable\fP BindingsImpl::bound (\fBToken\fP token)"
.PP
Reimplemented from \fBBindings\fP.
.PP
Definition at line 39 of file BindingsImpl.java.
.SS "\fBBindings\fP BindingsImpl::disjointUnion (\fBBindings\fP bindings)"
.PP
Reimplemented from \fBBindings\fP.
.PP
Definition at line 52 of file BindingsImpl.java.
.SS "Map BindingsImpl::mapValue ()"
.PP
Reimplemented from \fBBindings\fP.
.PP
Definition at line 29 of file BindingsImpl.java.
.SS "\fBBindings\fP BindingsImpl::overriding (\fBBindings\fP bindings)"
.PP
Reimplemented from \fBBindings\fP.
.PP
Definition at line 46 of file BindingsImpl.java.
.SS "String BindingsImpl::toString ()"
.PP
Reimplemented from \fBDataImpl\fP.
.PP
Definition at line 65 of file BindingsImpl.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.