.TH "BoolImpl" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoolImpl \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatumImpl\fP, and \fBBool\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "boolean \fBbooleanValue\fP ()"
.br
.ti -1c
.RI "\fBBool\fP \fBnot\fP ()"
.br
.ti -1c
.RI "\fBEmpty\fP \fBequals\fP (\fBData\fP data) throws \fBExceptional\fP"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "boolean BoolImpl::booleanValue ()"
.PP
Reimplemented from \fBBool\fP.
.PP
Definition at line 17 of file BoolImpl.java.
.SS "\fBEmpty\fP BoolImpl::equals (\fBData\fP data)"
.PP
Reimplemented from \fBDataValueImpl\fP.
.PP
Definition at line 25 of file BoolImpl.java.
.SS "\fBBool\fP BoolImpl::not ()"
.PP
Reimplemented from \fBBool\fP.
.PP
Definition at line 21 of file BoolImpl.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.