.TH "Bool" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bool \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatum\fP.
.PP
Inherited by \fBBoolImpl\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "boolean \fBbooleanValue\fP ()"
.br
.ti -1c
.RI "Bool \fBnot\fP ()"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "boolean Bool::booleanValue ()"
.PP
Reimplemented in \fBBoolImpl\fP.
.SS "Bool Bool::not ()"
.PP
Reimplemented in \fBBoolImpl\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.