.TH "DataImpl.java" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataImpl.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBProvide::_Provide\fP"
.br
.ti -1c
.RI "class \fBDataImpl\fP"
.br
.ti -1c
.RI "class \fBProvide\fP"
.br
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.