.TH "DataConst" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataConst \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDataValue\fP.
.PP
Inherited by \fBDataConstImpl\fP, and \fBEmpty\fP.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.