.TH "DatumImpl" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatumImpl \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDataValueImpl\fP, and \fBDatum\fP.
.PP
Inherited by \fBActionImpl\fP, \fBAgentImpl\fP, \fBBindingsImpl\fP, \fBBoolImpl\fP, \fBCellImpl\fP, \fBIntImpl\fP, \fBListImpl\fP, and \fBTextImpl\fP.
.PP
.SS "Protected Methods"

.in +1c
.ti -1c
.RI "\fBDatumImpl\fP (\fBPureFactory\fP factory)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "DatumImpl::DatumImpl (\fBPureFactory\fP factory)\fC [protected]\fP"
.PP
Definition at line 8 of file DatumImpl.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.