.TH "Datum" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Datum \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDataValue\fP, \fBBindable\fP, \fBStorable\fP, and \fBMessage\fP.
.PP
Inherited by \fBAction\fP, \fBAgent\fP, \fBBindings\fP, \fBBool\fP, \fBCell\fP, \fBDatumImpl\fP, \fBInt\fP, \fBList\fP, and \fBText\fP.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.