.TH "EmptyImpl" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmptyImpl \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDataConstImpl\fP, and \fBEmpty\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBDataValue\fP \fBat\fP (int n) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBDataValue\fP \fBfirst\fP () throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBData\fP \fBconcat\fP (\fBData\fP data)"
.br
.ti -1c
.RI "\fBList\fP \fBtupleToList\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBDataValue\fP EmptyImpl::at (int n)"
.PP
Reimplemented from \fBDataValueImpl\fP.
.PP
Definition at line 26 of file EmptyImpl.java.
.SS "\fBData\fP EmptyImpl::concat (\fBData\fP data)"
.PP
Reimplemented from \fBDataValueImpl\fP.
.PP
Definition at line 34 of file EmptyImpl.java.
.SS "\fBDataValue\fP EmptyImpl::first ()"
.PP
Reimplemented from \fBDataValueImpl\fP.
.PP
Definition at line 30 of file EmptyImpl.java.
.SS "String EmptyImpl::toString ()"
.PP
Reimplemented from \fBDataImpl\fP.
.PP
Definition at line 42 of file EmptyImpl.java.
.SS "\fBList\fP EmptyImpl::tupleToList ()"
.PP
Reimplemented from \fBDataValueImpl\fP.
.PP
Definition at line 38 of file EmptyImpl.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.