.TH "Enactable" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enactable \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBAbstractEnactable\fP, And::_And, AndExceptionally::_AndExceptionally, AndThen::_AndThen, Exceptionally::_Exceptionally, Hence::_Hence, Indivisibly::_Indivisibly, Otherwise::_Otherwise, Provide::_Provide, and Then::_Then.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBData\fP \fBenact\fP (\fBData\fP data, \fBBindings\fP bindings) throws \fBExceptional\fP, \fBFailed\fP, \fBUnfold\fP"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBData\fP Enactable::enact (\fBData\fP data, \fBBindings\fP bindings)"
.PP
Referenced by Indivisibly::enact(), Hence::enact(), Otherwise::enact(), AndExceptionally::enact(), Exceptionally::enact(), And::enact(), AndThen::enact(), Then::enact(), and ActionImpl::enact().
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.