.TH "Exceptional" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exceptional \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBException\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBData\fP \fBgetData\fP ()"
.br
.ti -1c
.RI "\fBExceptional\fP (\fBData\fP data)"
.br
.ti -1c
.RI "\fBExceptional\fP (String s, \fBData\fP data)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "Exceptional::Exceptional (\fBData\fP data)"
.PP
Definition at line 13 of file Exceptional.java.
.SS "Exceptional::Exceptional (String s, \fBData\fP data)"
.PP
Definition at line 19 of file Exceptional.java.
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBData\fP Exceptional::getData ()"
.PP
Definition at line 9 of file Exceptional.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.