.TH "Hence" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hence \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBAbstractInfixCombinator\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBHence\fP (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.br
.ti -1c
.RI "\fBData\fP \fBenact\fP (\fBData\fP data, \fBBindings\fP bindings) throws \fBExceptional\fP, \fBFailed\fP"
.br
.ti -1c
.RI "\fBHence\fP (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "Hence::Hence (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.PP
Definition at line 145 of file AbstractAction.java.
.SS "Hence::Hence (\fBPureFactory\fP factory, \fBEnactable\fP enactable1, \fBEnactable\fP enactable2)"
.PP
Definition at line 183 of file ActionImpl.java.
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBData\fP Hence::enact (\fBData\fP data, \fBBindings\fP bindings)"
.PP
Definition at line 148 of file AbstractAction.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.