.TH "Indivisibly" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Indivisibly \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBAbstractPrefixCombinator\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBIndivisibly\fP (\fBPureFactory\fP factory, \fBEnactable\fP action)"
.br
.ti -1c
.RI "\fBData\fP \fBenact\fP (\fBData\fP data, \fBBindings\fP bindings) throws \fBExceptional\fP, \fBFailed\fP"
.br
.ti -1c
.RI "\fBIndivisibly\fP (\fBPureFactory\fP factory, \fBEnactable\fP \fBenactable1\fP)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "Indivisibly::Indivisibly (\fBPureFactory\fP factory, \fBEnactable\fP enactable1)"
.PP
Definition at line 156 of file AbstractAction.java.
.SS "Indivisibly::Indivisibly (\fBPureFactory\fP factory, \fBEnactable\fP enactable1)"
.PP
Definition at line 198 of file ActionImpl.java.
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBData\fP Indivisibly::enact (\fBData\fP data, \fBBindings\fP bindings)"
.PP
Definition at line 159 of file AbstractAction.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.