.TH "Int" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Int \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatum\fP.
.PP
Inherited by \fBIntImpl\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "long \fBintValue\fP ()"
.br
.ti -1c
.RI "Int \fBplus\fP (Int n)"
.br
.ti -1c
.RI "Int \fBminus\fP (Int n)"
.br
.ti -1c
.RI "Int \fBmonus\fP (Int n)"
.br
.ti -1c
.RI "Int \fBtimes\fP (Int n)"
.br
.ti -1c
.RI "\fBEmpty\fP \fBgreater\fP (Int n) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBEmpty\fP \fBgreaterOrEq\fP (Int n) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBEmpty\fP \fBless\fP (Int n) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBEmpty\fP \fBlessOrEq\fP (Int n) throws \fBExceptional\fP"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBEmpty\fP Int::greater (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "\fBEmpty\fP Int::greaterOrEq (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "long Int::intValue ()"
.PP
Reimplemented in \fBIntImpl\fP.
.PP
Referenced by IntImpl::greater(), IntImpl::greaterOrEq(), IntImpl::less(), IntImpl::lessOrEq(), IntImpl::minus(), IntImpl::monus(), IntImpl::plus(), and IntImpl::times().
.PP
.SS "\fBEmpty\fP Int::less (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "\fBEmpty\fP Int::lessOrEq (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "Int Int::minus (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "Int Int::monus (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "Int Int::plus (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.
.SS "Int Int::times (Int n)"
.PP
Reimplemented in \fBIntImpl\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.