.TH "MessageTag" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageTag \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBText\fP.
.PP
Inherited by \fBMessageTagImpl\fP.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.