.TH "MessageTag.java" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageTag.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "interface \fBMessageTag\fP"
.br
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.