.TH "Provide" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Provide \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBActionImpl\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBProvide\fP (\fBPureFactory\fP factory, \fBData\fP data)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "Provide::Provide (\fBPureFactory\fP factory, \fBData\fP data)"
.PP
Definition at line 64 of file DataImpl.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.