.TH "Storing" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Storing \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBStore\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBCell\fP \fBcreate\fP (\fBStorable\fP storable)"
.br
.ti -1c
.RI "\fBEmpty\fP \fBdestroy\fP (\fBCell\fP cell) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBEmpty\fP \fBupdate\fP (\fBCell\fP cell, \fBStorable\fP o) throws \fBExceptional\fP"
.br
.ti -1c
.RI "\fBStorable\fP \fBinspect\fP (\fBCell\fP cell) throws \fBExceptional\fP"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBCell\fP Storing::create (\fBStorable\fP o)"
.PP
Reimplemented in \fBStore\fP.
.SS "\fBEmpty\fP Storing::destroy (\fBCell\fP cell)"
.PP
Reimplemented in \fBStore\fP.
.SS "\fBStorable\fP Storing::inspect (\fBCell\fP cell)"
.PP
Reimplemented in \fBStore\fP.
.SS "\fBEmpty\fP Storing::update (\fBCell\fP cell, \fBStorable\fP o)"
.PP
Reimplemented in \fBStore\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.