.TH "TextImpl" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextImpl \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatumImpl\fP, and \fBText\fP.
.PP
Inherited by \fBMessageTagImpl\fP, and \fBTokenImpl\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "String \fBstringValue\fP ()"
.br
.ti -1c
.RI "\fBEmpty\fP \fBequals\fP (\fBData\fP data) throws \fBExceptional\fP"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBEmpty\fP TextImpl::equals (\fBData\fP data)"
.PP
Reimplemented from \fBDataValueImpl\fP.
.PP
Definition at line 19 of file TextImpl.java.
.SS "String TextImpl::stringValue ()"
.PP
Reimplemented from \fBText\fP.
.PP
Definition at line 14 of file TextImpl.java.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.