.TH "Text" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBDatum\fP.
.PP
Inherited by \fBMessageTag\fP, \fBTextImpl\fP, and \fBToken\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "String \fBstringValue\fP ()"
.br
.in -1c
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "String Text::stringValue ()"
.PP
Reimplemented in \fBTextImpl\fP.
.PP
Referenced by TokenImpl::compareTo(), and TokenImpl::toString().
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.