.TH "Token" 3 "13 Sep 2002" "Action Java Compiler Runtime" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBText\fP, and \fBComparable\fP.
.PP
Inherited by \fBTokenImpl\fP.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Action Java Compiler Runtime from the source code.